### ISSUE TITLE
Test failures for cat_1 test

### ISSUE THREAD

**Issue by elliotlarson** [MeasureAuthoringTool/health-data-standards#503]
I'm trying to run the Cat 1 export test `test/unit/export/cat_1_test.rb` and I'm getting test failures.

```bash
$ ruby test/unit/export/cat_1_test.rb
Started with run options --seed 12363

Cat1Test
  test_record_target_export                                       PASS (0.64s)
  test_payer_information                                          PASS (0.64s)
  test_unique_data_criteria                                       PASS (0.70s)
  test_reporting_parameters_section_export                        PASS (0.62s)
Testing Cat I for Barry Berry
Testing Cat I for Mary Berry
  test_schematron_r2_validation                                   FAIL (6.39s)
Minitest::Assertion:         Invalid Cat I for Mary Berry (with header).
        --- expected
        +++ actual
        @@ -1 +1 @@
        -[]
        +[#<ValidationError:0xXXXXXX @location="/*[local-name()='ClinicalDocument' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='structuredBody' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3'][3]/*[local-name()='section' and namespace-uri()='urn:hl7-org:v3']", @message="SHALL contain at least one [1..*] entry (CONF:14567).", @validator="QRDA Cat 1 Validator", @file_name="cat1_good.xml">]
        test/unit/export/cat_1_test.rb:78:in `block in test_schematron_r2_validation'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:648:in `yield_document'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:123:in `block in each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `block in each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:122:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:20:in `each'
        test/unit/export/cat_1_test.rb:67:in `test_schematron_r2_validation'

  test_entries_for_data_criteria                                  FAIL (0.72s)
Minitest::Assertion:         Expected: 1
          Actual: 0
        test/unit/export/cat_1_test.rb:105:in `test_entries_for_data_criteria'

  test_patient_data_section_export                                FAIL (0.67s)
Minitest::Assertion:         med_dispensed is nil
        test/unit/export/cat_1_test.rb:95:in `test_patient_data_section_export'

Testing Cat I for Barry Berry
Testing Cat I for Mary Berry
  test_schematron_validation                                      FAIL (7.30s)
Minitest::Assertion:         Invalid Cat I for Mary Berry (with header).
        --- expected
        +++ actual
        @@ -1 +1 @@
        -[]
        +[#<ValidationError:0xXXXXXX @location="/*[local-name()='ClinicalDocument' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='structuredBody' and namespace-uri()='urn:hl7-org:v3']/*[local-name()='component' and namespace-uri()='urn:hl7-org:v3'][3]/*[local-name()='section' and namespace-uri()='urn:hl7-org:v3']", @message="SHALL contain at least one [1..*] entry (CONF:14567).", @validator="QRDA Cat 1 R3 Validator", @file_name="cat1_good.xml">]
        test/unit/export/cat_1_test.rb:60:in `block in test_schematron_validation'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:648:in `yield_document'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:123:in `block in each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `block in each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:122:in `each'
        /Users/pairing/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:20:in `each'
        test/unit/export/cat_1_test.rb:49:in `test_schematron_validation'

Testing Cat I for Barry Berry
Testing Cat I for Mary Berry
Testing Cat I for Rosa Vasquez
  test_schema_validation                                          PASS (0.87s)
  test_handling_expired_patients                                  PASS (0.67s)
  test_cda_header_export                                          PASS (0.63s)
  test_measure_section_export                                     PASS (0.58s)

Finished in 20.44585s
12 tests, 28 assertions, 4 failures, 0 errors, 0 skips
```

I'm using Ruby 2.2.1 and mongo 3.4.4.

**Comment by dczulada** [comment]
I can't recreate this.  (I realize this response is a little dated) If you are still having this issue, what branch are you developing against?

**Comment by elliotlarson** [comment]
Oh, that was over a year ago.  Not sure  ¯\\\_(ツ)\_/¯.
